### ISSUE TITLE
v1.0 Roadmap

### ISSUE THREAD

**Issue by nderscore** [nderscore/runty#1]
This space is for broadly planning out the path to runty v1.0 and is subject to continuous change.

# Musts
* [x] Core Functionality
  * [x] Parser/Lexer
  * [x] Template execution
* [x] Useful Error Messages
* [ ] Documentation
  * [x] Grammar / Syntax
  * [x] API Docs: Core library
  * [x] API Docs: Standard library (`fns`)
  * [x] Guide: Extending with custom functions
  * [ ] Guide: Usage with React
* [x] Expand Standard Library
* [x] 100% Unit Test Coverage
  * [x] Core functionality
  * [x] Standard library (`fns`)
  * [x] Error scenarios
* [ ] Stress Testing
  * [ ] Function and Expression nesting depth (`{%a?{%b?%c?$d($e(%f,$g()))?{%f}}}`)
  * [ ] Excessively long property accessor chains (`%a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z`)

# Maybe Laters
* [x] Typescript - Convert to typescript? Or export type declarations?
* [x] Documentation Website
* [x] CI Pipeline Package Publishing
* [ ] Stress Testing
  * [ ] Function and Expression nesting depth (`{%a?{%b?%c?$d($e(%f,$g()))?{%f}}}`)
  * [ ] Excessively long property accessor chains (`%a.b.c.d.e.f.g.h.i.j.k.l.m.n.o.p.q.r.s.t.u.v.w.x.y.z`)
* [ ] Performance Testing/Improvement

**Comment by eberens-nydig** [comment]
+1 on Typescript support
